ALTER TABLE "person" ADD COLUMN IF NOT EXISTS "nationality" VARCHAR(100);
ALTER TABLE "person" ADD COLUMN IF NOT EXISTS "bio_summary" TEXT;

ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "patron_saint" VARCHAR(200);
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "cathedral_dedication" VARCHAR(200);
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "catholic_population" INTEGER;
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "total_population" INTEGER;
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "num_parishes" INTEGER;
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "square_miles" INTEGER;
ALTER TABLE "see" ADD COLUMN IF NOT EXISTS "is_usccb_territory" BOOLEAN DEFAULT false;
